name: f1stats
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  html: ^0.15.4
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/ # Ensure the directory structure matches

  fonts:
    - family: Formula1
      fonts:
        - asset: assets/fonts/Formula1-Black.ttf
          weight: 900
        - asset: assets/fonts/Formula1-Bold.ttf
          weight: 700
        - asset: assets/fonts/Formula1-Regular.ttf
        - asset: assets/fonts/Formula1-Wide.ttf
